# For your production deployments, you probably want to run CI on ALL branches.
# You may have separate CI (lighter-weight) processes for your Dev/* builds...

trigger:
  branches:
    include:
      - main
      - dev*
  batch: true
  # including the path filter for future use.
  paths:
    include:
      - source/SolutionInfrastructure
      - pipelines/iac_solution_build.yaml
      - pipelines/iac_solution_deploy.yaml
      - pipelines/templates/iac_build_stageTemplate.yaml
      - pipelines/templates/solution_deploy_stageTemplate.yaml
    exclude:
      - source/SolutionInfrastructure/readme.md

variables:
- name: v_filePathToFiles
  value: '$(Build.SourcesDirectory)\source\SolutionInfrastructure\'
- name: v_serviceConnectionName
  value: 'DataOpsAzSvcEndpoint'

pool:
  vmImage: 'windows-latest'

stages:
  - template: templates/iac_build_stageTemplate.yaml
    parameters:
      t_p_filePathToFiles: '${{ variables.v_filePathToFiles }}'
      t_p_serviceConnection: '${{ variables.v_serviceConnectionName }}'
